server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** #添加商品微服务
    search-service: /search/** #添加搜索微服务
    user-service: /user/** #添加用户微服务
    auth-service: /auth/**
    order-service: /order/**
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 500
  add-host-header: true
  sensitive-headers: # //覆盖敏感头信息，把Cookie和Set-Cookie里面的内容给覆盖了
leyou:
  jwt:
    pubKeyPath:  C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
