server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.81.128:3306/hm53
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  spring:
    redis:
      host: 192.168.81.128
    rabbitmq:
      host: 192.168.81.128
      username: leyou
      password: leyou
      virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo
